name: carp_mobile_sensing_example
description: Examples of how to use the carp_mobile_sensing framework.
publish_to: 'none'
version: 1.6.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"


dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  carp_core: ^1.1.0
  # carp_serializable:
  #   path: ../../carp_serializable/
  # carp_core:
  #   path: ../../carp_core
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  
  http: ^1.2.1
  json_annotation: ^4.8.0

dependency_overrides:

dev_dependencies:
  test: any
  flutter_lints: any
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true
