name: carp_mobile_sensing_example
description: Examples of how to use the carp_mobile_sensing framework.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # carp_serializable:
  #   path: ../../carp_serializable/
  # carp_core:
  #   path: ../../carp_core
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/

dependency_overrides:

dev_dependencies:
  test: any
  flutter_lints: any

flutter:
  uses-material-design: true
