name: carp_communication_package
description: CARP communication sampling package. Samples phone, sms, and calendar logs and activity.
version: 1.1.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_communication_package

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # carp_serializable: ^1.1.0
  # carp_core: ^1.1.0
  # carp_mobile_sensing: ^1.1.0

  json_annotation: ^4.8.0
  telephony: ^0.2.0
  call_log: ^4.0.0
  device_calendar: ^4.3.0
  crypto: ^3.0.1
  permission_handler: ^10.3.0  
  
# Overriding carp libraries to use the local copy.
# Remove this before release of package.
dependency_overrides:
  carp_serializable:
    path: ../../carp_serializable/
  carp_core:
    path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/

dev_dependencies:
  flutter_lints: any
  build_runner: any
  json_serializable: any
  test: any

flutter:
