name: carp_webservices_example
description: An small example of how to usee the CARP web service package.
homepage: https://github.com/cph-cachet/carp.sensing-flutter
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  carp_core: ^1.8.0
  carp_mobile_sensing: ^1.11.0

  # carp_core:
  #   path: ../../../carp_core
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_webservices:
    path: ../

  oidc: ^0.9.0+1

dev_dependencies:
  test: any
  flutter_lints: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
