name: carp_mobile_sensing_app
description: The CARP Mobile Sensing App
version: 1.4.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/apps/carp_mobile_sensing_app
publish_to: 'none' 

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  permission_handler: ^11.0.1
  
  carp_serializable: ^1.1.0
  #carp_core: ^0.30.0
  #carp_mobile_sensing: ^0.30.6
  #carp_connectivity_package: ^0.30.0
  #carp_context_package: ^0.30.1
  #carp_audio_package: ^0.30.0
  #carp_communication_package: ^0.30.0
  #carp_apps_package: ^0.30.0
  #carp_backend: ^0.30.0
  #carp_webservices: ^0.30.0
  #carp_health_package: ^2.0.0
  #carp_firebase_backend: ^0.30.0

  # carp_esense_package: ^0.30.2
  # carp_movisens_package: ^0.32.0

  research_package: ^1.2.0
  # health: ^8.1.0

# Overriding carp libraries to use the local copy
dependency_overrides:
  # carp_serializable:
  #   path: ../../carp_serializable/
  carp_core:
    path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  carp_context_package:
    path: ../../packages/carp_context_package/
  carp_connectivity_package:
    path: ../../packages/carp_connectivity_package/
  carp_communication_package:
    path: ../../packages/carp_communication_package/
  carp_audio_package:
    path: ../../packages/carp_audio_package/
  carp_apps_package:
    path: ../../packages/carp_apps_package/
  carp_esense_package:
    path: ../../packages/carp_esense_package/
  carp_polar_package:
    path: ../../packages/carp_polar_package/
  carp_movisens_package:
    path: ../../packages/carp_movisens_package/
  carp_health_package:
    path: ../../packages/carp_health_package/
  carp_backend:
    path: ../../backends/carp_backend/
  carp_webservices:
    path: ../../backends/carp_webservices/
  carp_movesense_package:
    path: ../../packages/carp_movesense_package/

  # research_package:
  #   path: ../../../../research.package/
  # esense_flutter:
  #   path: ../../../../flutter-plugins/packages/esense_flutter/
  # location:
  #   git:
  #     url: https://github.com/fairuzmn/flutterlocation.git
  #     ref: location-v5.5.0.0-dev.9-fix
  #     path: packages/location

dev_dependencies:
  flutter_test:
    sdk: flutter  
  test: any 
  flutter_lints: any
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/cachet_logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/study.png
    - assets/cachet_logo.png
    - assets/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
