name: carp_survey_package
description: CARP survey sampling package. Samples survey data from the CARP Research Package and Cognition Package.
version: 1.5.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_survey_package

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  carp_core: ^1.6.0
  # carp_mobile_sensing: ^1.6.0

  research_package: ^1.4.0
  cognition_package: ^1.5.0
  json_annotation: ^4.8.0
  permission_handler: ^11.0.0  


# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_serializable:
  #   path: ../../carp_serializable/
  # carp_core:
  #   path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  # research_package: 
  #   path: ../../../../research.package/
  # cognition_package: 
  #   path: ../../../../cognition_package/
  

dev_dependencies:
  flutter_lints: any
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
