name: carp_core
description: The core domain model for the Copenhagen Research Platform (CARP) in Dart.
version: 1.3.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  json_annotation: ^4.8.0
  iso_duration_parser: ^1.1.0
  meta: ^1.8.0
  uuid: '>=3.0.1 <5.0.0'

# Overriding carp core libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
#   carp_serializable:
#     path: ../carp_serializable/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any   
  flutter_lints: any

# auto generate json code (.g files) with:
#   dart run build_runner build --delete-conflicting-outputs

