name: carp_esense_package_example
description: Example project for the CAMS eSense Package.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # carp_core:
  #   path: ../../../carp_core
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_esense_package:
    path: ../

dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
