name: carp_survey_package_example
description: Examples of how to use the carp_survey_package.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carp_core: ^1.1.0
  carp_mobile_sensing: ^1.1.0
  # carp_core:
  #   path: ../../../carp_core
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_survey_package:
    path: ../
