name: carp_movesense_package
description: The CARP Movesense sampling package. Samples sensor data from the Movesense MD and ACTIVE (HR+, HR2) devices.
homepage: https://github.com/cph-cachet/carp.sensing-flutter
version: 1.6.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^2.0.0
  carp_core: ^1.8.0
  carp_mobile_sensing: ^1.10.0

  mdsflutter: ^2.0.0 
  json_annotation: ^4.8.0


#dependency_overrides:
 # carp_serializable:
  #  path: ../../carp_serializable/    
  #carp_core:
  #  path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  test: any
  flutter_lints: any  
