name: carp_movesense_package
description: The CARP Movesense sampling package. Samples sensor data from the Movesense MD and FLASH devices.
version: 1.4.0
homepage:
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0
  carp_core: ^1.4.0
  carp_mobile_sensing: ^1.4.0

  mdsflutter: ^2.0.0 
  permission_handler: ^11.0.1
  json_annotation: ^4.8.0
  flutter_activity_recognition: ^3.0.0
  package_info_plus: ^5.0.0
  device_info_plus: ^9.1.0
  async: ^2.11.0


#dependency_overrides:
 # carp_serializable:
  #  path: ../../carp_serializable/    
  #carp_core:
  #  path: ../../carp_core/
  #carp_mobile_sensing:
   # path: ../../carp_mobile_sensing/


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  test: any
  flutter_lints: any  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
