name: carp_movesense_package_example
description: Example project for the CAMS Movesense Sampling Package.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carp_core: ^1.2.0
  carp_mobile_sensing: ^1.11.0
  # carp_core:
  #   path: ../../../carp_core
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_movesense_package:
    path: ../

dev_dependencies:
