name: carp_movisens_package_example
description: Examples of how to use the CANS Movisens Package.
version: 1.5.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  carp_core: ^1.4.0
  # carp_mobile_sensing: ^1.4.0
  # carp_core:
  #   path: ../../../carp_core
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_movisens_package:
    path: ../

dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
 