name: carp_polar_package
description: The CARP Polar sampling package. Samples sensor data from the Polar H9, H10, and Verity Sense devices.
version: 1.6.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_polar_package

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^2.0.0
  carp_core: ^1.8.0
  carp_mobile_sensing: ^1.10.0
 
  json_annotation: ^4.8.0
  polar: ^7.0.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
#   carp_serializable:
#     path: ../../carp_serializable/
#   carp_core:
#     path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any
  flutter_lints: any

