name: carp_serializable
description: Polymorphic JSON serialization based on json_serializable annotations.
version: 2.0.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  json_annotation: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any 
  json_serializable: any
  test: any

flutter:
