name: carp_serializable
description: Polymorphic JSON serialization based on json_serializable annotations.
version: 1.1.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
   sdk: '>=2.17.6 <4.0.0'
   flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  json_annotation: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any   # For building json serialization
  json_serializable: any
  test: any

flutter:

# Auto generate json code (.g files) with:
#   dart run build_runner build --delete-conflicting-outputs

